export const browserCoreExamples = [
  "zagent browser status",
  "zagent browser start",
  "zagent browser stop",
  "zagent browser tabs",
  "zagent browser open https://example.com",
  "zagent browser focus abcd1234",
  "zagent browser close abcd1234",
  "zagent browser screenshot",
  "zagent browser screenshot --full-page",
  "zagent browser screenshot --ref 12",
  "zagent browser snapshot",
  "zagent browser snapshot --format aria --limit 200",
  "zagent browser snapshot --efficient",
  "zagent browser snapshot --labels",
];

export const browserActionExamples = [
  "zagent browser navigate https://example.com",
  "zagent browser resize 1280 720",
  "zagent browser click 12 --double",
  'zagent browser type 23 "hello" --submit',
  "zagent browser press Enter",
  "zagent browser hover 44",
  "zagent browser drag 10 11",
  "zagent browser select 9 OptionA OptionB",
  "zagent browser upload /tmp/file.pdf",
  'zagent browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "zagent browser dialog --accept",
  'zagent browser wait --text "Done"',
  "zagent browser evaluate --fn '(el) => el.textContent' --ref 7",
  "zagent browser console --level error",
  "zagent browser pdf",
];
